name: start automatic deployment for triggr app on main

on:
  push:
    branches:
      - main

jobs:
  curl:
    runs-on: ubuntu-latest
    env:
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Get latest commit SHA
        run: echo ${{ github.sha }} >> $GITHUB_ENV
      - name: Perform curl request
        run: |
          curl -H "Authorization: Bearer $BEARER_TOKEN" -H "X-Commit-SHA: $COMMIT_SHA" https://b6ed-102-88-35-226.eu.ngrok.io/v1/provider/webhook/triggr/automaticDeployment